"""Stable normalized telemetry vocabulary.

Unknown simulator channels are retained by ingestion provenance but are not silently
promoted to normalized concepts. New concepts require a contract version review.
"""

PROVENANCE_KINDS = {"measured", "derived", "estimated", "unavailable"}

NORMALIZED_CONCEPTS = {
    "timestamp",
    "lap_time",
    "lap_valid",
    "lap_distance",
    "track_position_x",
    "track_position_y",
    "track_position_z",
    "speed",
    "longitudinal_acceleration",
    "lateral_acceleration",
    "vertical_acceleration",
    "yaw_rate",
    "steering_angle",
    "steering_input",
    "throttle",
    "brake",
    "clutch",
    "gear",
    "rpm",
    "wheel_speed_front_left",
    "wheel_speed_front_right",
    "wheel_speed_rear_left",
    "wheel_speed_rear_right",
    "tire_pressure_front_left",
    "tire_pressure_front_right",
    "tire_pressure_rear_left",
    "tire_pressure_rear_right",
    "tire_temperature_front_left",
    "tire_temperature_front_right",
    "tire_temperature_rear_left",
    "tire_temperature_rear_right",
    "abs_active",
    "traction_control_active",
    "fuel_mass",
    "session_state",
    "incident_state",
    "off_track_state",
    "air_temperature",
    "track_temperature",
    "track_wetness",
}

RECORD_TYPES = {
    "session",
    "lap",
    "segment",
    "telemetry_sample",
    "driver_input_event",
}

# Canonical normalized units are contract semantics, not display preferences.
CANONICAL_UNITS = {
    "timestamp": "s",
    "lap_time": "s",
    "lap_valid": "boolean",
    "lap_distance": "m",
    "track_position_x": "m",
    "track_position_y": "m",
    "track_position_z": "m",
    "speed": "m/s",
    "longitudinal_acceleration": "m/s^2",
    "lateral_acceleration": "m/s^2",
    "vertical_acceleration": "m/s^2",
    "yaw_rate": "rad/s",
    "steering_angle": "rad",
    "steering_input": "ratio",
    "throttle": "ratio",
    "brake": "ratio",
    "clutch": "ratio",
    "gear": "integer",
    "rpm": "1/min",
    "wheel_speed_front_left": "m/s",
    "wheel_speed_front_right": "m/s",
    "wheel_speed_rear_left": "m/s",
    "wheel_speed_rear_right": "m/s",
    "tire_pressure_front_left": "Pa",
    "tire_pressure_front_right": "Pa",
    "tire_pressure_rear_left": "Pa",
    "tire_pressure_rear_right": "Pa",
    "tire_temperature_front_left": "degC",
    "tire_temperature_front_right": "degC",
    "tire_temperature_rear_left": "degC",
    "tire_temperature_rear_right": "degC",
    "abs_active": "boolean",
    "traction_control_active": "boolean",
    "fuel_mass": "kg",
    "session_state": "state",
    "incident_state": "state",
    "off_track_state": "boolean",
    "air_temperature": "degC",
    "track_temperature": "degC",
    "track_wetness": "ratio",
}

CANONICAL_CONVENTIONS = {
    "vehicle_frame": "right_handed_x_forward_y_left_z_up",
    "steering_sign": "positive_left",
    "yaw_rate_sign": "positive_counterclockwise_viewed_from_above",
    "lateral_acceleration_sign": "positive_left",
    "longitudinal_acceleration_sign": "positive_forward",
    "track_position_frame": "right_handed_adapter_normalized",
}
